name: Sync Telegram Videos

on:
  workflow_dispatch:  # allows you to trigger it manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Debug session string length
        run: echo "Session string length is ${#TELEGRAM_SESSION_STRING} characters"
        env:
         TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
      - name: Run sync
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          SYNC_CHANNELS: ${{ secrets.SYNC_CHANNELS }}
          TELEGRAPH_ACCESS_TOKEN: ${{ secrets.TELEGRAPH_ACCESS_TOKEN || '' }}
          TELEGRAM_SESSION_STRING: BQDL1yoAhNwm9PYawG4bPDVE_rEkVCRdlo3AbPCqzfN9HzVXoMEZDiLwAZC9SPqUJCn2WEnfhufpWgtUU9l63KXX59ntztofGJTQgtgMwL1gxAFAFQTSSZ5LGqFy8sCqZpzaJMkY9EksmdyuSDyYi4FvhtJ-p48lhLOrg3Jnb_6tu_wbOSHsQpUiNCvrfoUrPU7jZ6-8LMUPvbwRbknvGz2ez9bCQmeylGHg50WR2xIKlSsrcZlGpkCaTocNqFbmHhslWviOI-_rL6A5NATWMoAuB4NsbF409FkLGyb8PYfuZMNnutStsZ9L3_ezsRm5wU7ja_v5rJvdBmutbWMr_p3E7VR9rwAAAABEGOf6AA
        run: python sync.py
